### ISSUE TITLE
Data persistence

### ISSUE THREAD

**Issue by pimuzzo** [greatfireball/Docker_LogicalDoc_Community#1]
This container is not data persistent, do you have any intentions to use volumes in the future?

**Comment by greatfireball** [comment]
Hey pimuzzo,

to be honest, I started that container to play a little bit with LogicalDoc... I would like to put more efforts into preparing the image, but currently I am a little busy. Starting in May I will finish the container and sure, volumes are planned to provide data persistence.

Do you plan to use LogicalDoc in a docker container?

Best,
Frank

**Comment by pimuzzo** [comment]
Yes, I plan to use LogicalDoc in a docker container, I appreciate any your contribute.
Thanks for now :+1:

**Comment by pimuzzo** [comment]
The project seems dead and I'm not working on it anymore, reopen if you think it's necessary
